/**
 * Madhyamaka / Nāgārjuna Analytical Heuristics
 * Based on the Mūlamadhyamakakārikā (MMK) dialectical method
 */

export interface MadhyamakaHeuristic {
  id: string;
  sanskritTerm: string;
  name: string;
  description: string;
  diagnosticQuestions: string[];
}

export const NAGARJUNA_HEURISTICS: MadhyamakaHeuristic[] = [
  {
    id: "H-SVABHAVA",
    sanskritTerm: "svabhāva",
    name: "Critique of Inherent / Intrinsic Existence",
    description: "Examines whether an entity, self, or property is treated as existing independently, by its own inherent nature, unconditioned by relations.",
    diagnosticQuestions: [
      "What entity is being treated as inherently existent (possessing svabhāva)?",
      "Is an identity being asserted as self-standing and unconditioned?",
      "Can this entity exist without depending on parts, causes, or an observer?"
    ]
  },
  {
    id: "H-PRATITYASAMUTPADA",
    sanskritTerm: "pratītyasamutpāda",
    name: "Dependent Arising / Relational Dependence",
    description: "Demonstrates that whatever exists arises in dependence on causes, conditions, and conceptual imputation. Independence is an illusion.",
    diagnosticQuestions: [
      "What causes and conditions does this entity depend upon?",
      "Does its identity exist only in relation to its opposite or complement (e.g. fire/fuel, observer/observed)?",
      "If it depends on conditions, how could it possess independent intrinsic reality?"
    ]
  },
  {
    id: "H-SUNYATA",
    sanskritTerm: "śūnyatā",
    name: "Emptiness of Intrinsic Essence",
    description: "Emptiness is not nothingness or nihilism; it is the absence of independent essence, which is the very condition that allows change and function to occur (MMK 24.14: 'For whom emptiness is possible, all things are possible').",
    diagnosticQuestions: [
      "Is emptiness being confused with non-existence (nihilism)?",
      "How does the lack of fixed essence allow this system to operate dynamically?"
    ]
  },
  {
    id: "H-PRAJNAPTI",
    sanskritTerm: "prajñapti-upādāya",
    name: "Conceptual Designation / Nominal Convention",
    description: "Things exist conventionally as pragmatic linguistic designations, not as ultimate metaphysical substances.",
    diagnosticQuestions: [
      "Is a useful conceptual label being reified into a cosmic object?",
      "Does this word function as a conventional sign without needing an underlying metaphysical substance?"
    ]
  },
  {
    id: "H-PRASANGA",
    sanskritTerm: "prasaṅga",
    name: "Dialectical Reductio / Internal Contradiction",
    description: "Shows that asserting inherent existence creates insurmountable logical contradiction (e.g. if an effect inherently exists in the cause, it doesn't need to arise; if it doesn't exist in the cause, it cannot arise from it).",
    diagnosticQuestions: [
      "Does claiming inherent reality for this concept make change, causality, or relation impossible?",
      "What internal contradiction is generated by the opponent's thesis?"
    ]
  },
  {
    id: "H-CATUSKOTI",
    sanskritTerm: "catuṣkoṭi",
    name: "Tetralemma / Four-Cornered Negation",
    description: "Negation of the four conceptual extremes regarding any proposed entity: it is not A, not ~A, not both, not neither.",
    diagnosticQuestions: [
      "Does the claim assume a simplistic binary of either 'it truly exists' or 'it is nothing'?",
      "How do all four conceptual corners fail to capture dependent reality?"
    ]
  }
];
